spring:
  redis:
    cluster:
      nodes:
      - 127.0.0.1:6379
      - 127.0.0.1:6380
      - 127.0.0.1:6381
      - 127.0.0.1:6382
      - 127.0.0.1:6383
      - 127.0.0.1:6384
      max-redirects: 3
    timeout: 10
    pool:
      max-active: 10
      max-idle: 10
      min-idle: 0
      max-wait: 5000
    host: 127.0.0.1
    port: 6379

